title: "Networking & Automation"
author: "Splash Networks"
description: "Powered By <b style=\"color: #f45;\">Splash Networks</b>"
permalink: /:title/
lang: "en"
#excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# ADDED BY NASIR

excerpt_separator: "<!--more-->"
# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}
  - {file: "README.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:hello@splashnetworks.co"}
  - {title: Youtube, icon: youtube, url: "https://www.youtube.com/@splashnetworksco"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/company/splash-networks/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed